### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by lhzwb2008** [PixelsMetaverse/pixels-metaverse#3]
yarn install success,but yarn start with this error:
Attempted import error: 'CanvasSlicImg' is not exported from '../../pixels-metaverse'.

**Comment by qianduanxinlv** [comment]
> yarn install success,but yarn start with this error: Attempted import error: 'CanvasSlicImg' is not exported from '../../pixels-metaverse'.

Sorry, since I need to make some upgrades to the feature to participate in the contest, the code has not been released yet, so the update to the  _**react-pixel-metaverse**_  package has not been released yet, so you may not find the corresponding  _**CanvasSlicImg**_  component.
很抱歉，由于我需要对功能进行一些升级才能参与黑客松比赛，对react-pixel-metaverse包的更新尚未发布，因此您可能找不到相应的CanvasSlicImg组件。
You can now access the link   [](https://github.com/xiangzhengfeng/pixels-metavers) , which was the previous version, but can be used for learning. In addition, the project will be released once before Christmas, and then you can see that the warehouse code is working properly. Thank you for your attention and hope we can make progress together.
当前您可以访问链接 https://github.com/xiangzhengfeng/pixels-metavers，这是以前的版本，但可用于学习。此外，该项目 [](https://github.com/PixelsMetaverse/pixels-metaverse) 将在圣诞节前发布一次，到时候您可以看到仓库代码正常工作了。感谢您的关注，希望我们能共同进步。
